projectType: extension
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -DruntimeVersion=4.4.0
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DminVersion=4.6.0 -DruntimeVersion=4.6.0-rc2 -DruntimeProduct=MULE_EE